name: GPG Decrypt
on: [ push ]
jobs:
  decrypt_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$MY_SECRET_FILE" --output $HOME/decrypted.json file_with_secrets.json.gpg 
        env:
          MY_SECRET_FILE: ${{ secrets.MY_SECRET_FILE }}
      - name: Print our secret file contents
        run: cat $HOME/decrypted.json
